version: '3.8'
services:
  dynamodb-local:
    image: amazon/dynamodb-local:1.13.4
    ports:
      - 8000:8000
  go-app:
    image: lambda-practice/go-app
    build:
      context: .
      dockerfile: ./Dockerfile.go-app
      target: development
    command: bash
    tty: true
    volumes:
      - type: bind
        source: ${PWD}/app2
        target: /root/app
      - type: bind
        source: ${PWD}/go-pkg
        target: /go/pkg
    environment:
      DYNAMO_LOCAL_ENDPOINT: http://dynamodb-local:8000
      DYNAMO_TABLE_NAME: ResourceTable
      DYNAMO_PK_NAME: PK
      DYNAMO_SK_NAME: SK
      AWS_ACCESS_KEY_ID: dummy
      AWS_SECRET_ACCESS_KEY: dummy

networks:
  default:
    ipam:
      config:
        - subnet: 192.168.255.0/24
